% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={MEDI 504B - Exploratory Data Analysis},
  pdfauthor={Erick Navarro \& Timo Tolppa},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{MEDI 504B - Exploratory Data Analysis}
\author{Erick Navarro \& Timo Tolppa}
\date{2023-01-11}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{4}
\tableofcontents
}
\hypertarget{introduction}{%
\subsection{1 Introduction}\label{introduction}}

The goal of this report is to conduct an exploratory data analysis (EDA)
of
\href{https://www.kaggle.com/datasets/prasoonkottarathil/polycystic-ovary-syndrome-pcos?resource=download}{a
publicly available dataset} of polycystic ovary syndrom (PCOS), a
hormonal disorder common among women of reproductive age.

This is the first step of the course project of developing a model to
diagnose PCOS. On this deliverable, I will explore the dataset, clean
it, and understand its variables.

\hypertarget{data-preparation-pre-processing}{%
\subsection{2 Data Preparation \&
Pre-processing}\label{data-preparation-pre-processing}}

\hypertarget{load-libraries-and-data-files}{%
\subsubsection{2.1 Load libraries and data
files}\label{load-libraries-and-data-files}}

The packages that need to be installed for this exploratory data
analysis include `janitor', `tidyverse', `DataExplorer', `skimr',
`here', `knitr' and `readxl.' The names of the columns are cleaned using
the janitor package.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load required libraries}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(here)}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(janitor)}
\FunctionTok{library}\NormalTok{(DataExplorer)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(skimr)}
\FunctionTok{library}\NormalTok{(cowplot)}

\CommentTok{\# Load the data file to a data frame}
\NormalTok{data }\OtherTok{=} \FunctionTok{read\_excel}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"PCOS\_data\_without\_infertility.xlsx"}\NormalTok{), }\AttributeTok{sheet =} \StringTok{"Full\_new"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{clean\_names}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\hypertarget{data-preprocessing}{%
\subsubsection{2.2 Data preprocessing}\label{data-preprocessing}}

An overview of the data is shown using `glimpse' and `skim'.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 541
## Columns: 45
## $ sl_no                <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15~
## $ patient_file_no      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15~
## $ pcos_y_n             <dbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0~
## $ age_yrs              <dbl> 28, 36, 33, 37, 25, 36, 34, 33, 32, 36, 20, 26, 2~
## $ weight_kg            <dbl> 44.6, 65.0, 68.8, 65.0, 52.0, 74.1, 64.0, 58.5, 4~
## $ height_cm            <dbl> 152.0, 161.5, 165.0, 148.0, 161.0, 165.0, 156.0, ~
## $ bmi                  <dbl> 19.30000, 24.92116, 25.27089, 29.67495, 20.06095,~
## $ blood_group          <dbl> 15, 15, 11, 13, 11, 15, 11, 13, 11, 15, 15, 13, 1~
## $ pulse_rate_bpm       <dbl> 78, 74, 72, 72, 72, 78, 72, 72, 72, 80, 80, 72, 7~
## $ rr_breaths_min       <dbl> 22, 20, 18, 20, 18, 28, 18, 20, 18, 20, 20, 20, 1~
## $ hb_g_dl              <dbl> 10.48, 11.70, 11.80, 12.00, 10.00, 11.20, 10.90, ~
## $ cycle_r_i            <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2~
## $ cycle_length_days    <dbl> 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 2, 5, 5, 5, 5~
## $ marraige_status_yrs  <dbl> 7, 11, 10, 4, 1, 8, 2, 13, 8, 4, 4, 3, 7, 15, 9, ~
## $ pregnant_y_n         <dbl> 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1~
## $ no_of_aborptions     <dbl> 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 0, 0, 0, 0, 0~
## $ i_beta_hcg_m_iu_m_l  <dbl> 1.99, 60.80, 494.08, 1.99, 801.45, 237.97, 1.99, ~
## $ ii_beta_hcg_m_iu_m_l <chr> "1.99", "1.99", "494.08", "1.99", "801.45", "1.99~
## $ fsh_m_iu_m_l         <dbl> 7.95, 6.73, 5.54, 8.06, 3.98, 3.24, 2.85, 4.86, 3~
## $ lh_m_iu_m_l          <dbl> 3.68, 1.09, 0.88, 2.36, 0.90, 1.07, 0.31, 3.07, 3~
## $ fsh_lh               <dbl> 2.160326, 6.174312, 6.295455, 3.415254, 4.422222,~
## $ hip_inch             <dbl> 36, 38, 40, 42, 37, 44, 39, 44, 39, 40, 39, 39, 4~
## $ waist_inch           <dbl> 30, 32, 36, 36, 30, 38, 33, 38, 35, 38, 35, 33, 4~
## $ waist_hip_ratio      <dbl> 0.8333333, 0.8421053, 0.9000000, 0.8571429, 0.810~
## $ tsh_m_iu_l           <dbl> 0.68, 3.16, 2.54, 16.41, 3.57, 1.60, 1.51, 12.18,~
## $ amh_ng_m_l           <chr> "2.07", "1.53", "6.63", "1.22", "2.26", "6.74", "~
## $ prl_ng_m_l           <dbl> 45.16, 20.09, 10.52, 36.90, 30.09, 16.18, 26.41, ~
## $ vit_d3_ng_m_l        <dbl> 17.10, 61.30, 49.70, 33.40, 43.80, 52.40, 42.70, ~
## $ prg_ng_m_l           <dbl> 0.57, 0.97, 0.36, 0.36, 0.38, 0.30, 0.46, 0.26, 0~
## $ rbs_mg_dl            <dbl> 92, 92, 84, 76, 84, 76, 93, 91, 116, 125, 108, 10~
## $ weight_gain_y_n      <dbl> 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0~
## $ hair_growth_y_n      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0~
## $ skin_darkening_y_n   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0~
## $ hair_loss_y_n        <dbl> 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0~
## $ pimples_y_n          <dbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0~
## $ fast_food_y_n        <dbl> 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0~
## $ reg_exercise_y_n     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0~
## $ bp_systolic_mm_hg    <dbl> 110, 120, 120, 120, 120, 110, 120, 120, 120, 110,~
## $ bp_diastolic_mm_hg   <dbl> 80, 70, 80, 70, 80, 70, 80, 80, 80, 80, 80, 80, 8~
## $ follicle_no_l        <dbl> 3, 3, 13, 2, 3, 9, 6, 7, 5, 1, 7, 4, 15, 3, 4, 1,~
## $ follicle_no_r        <dbl> 3, 5, 15, 2, 4, 6, 6, 6, 7, 1, 15, 2, 8, 3, 1, 3,~
## $ avg_f_size_l_mm      <dbl> 18, 15, 18, 15, 16, 16, 15, 15, 17, 14, 17, 18, 2~
## $ avg_f_size_r_mm      <dbl> 18, 14, 20, 14, 14, 20, 16, 18, 17, 17, 20, 19, 2~
## $ endometrium_mm       <dbl> 8.5, 3.7, 10.0, 7.5, 7.0, 8.0, 6.8, 7.1, 4.2, 2.5~
## $ x45                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skim}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule()
\endhead
Name & data \\
Number of rows & 541 \\
Number of columns & 45 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 3 \\
numeric & 42 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule()
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.2658}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1266}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1772}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0506}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0506}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0759}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1139}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1392}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule()
\endhead
ii\_beta\_hcg\_m\_iu\_m\_l & 0 & 1 & 3 & 8 & 0 & 203 & 0 \\
amh\_ng\_m\_l & 0 & 1 & 1 & 5 & 0 & 301 & 0 \\
x45 & 539 & 0 & 1 & 3 & 0 & 2 & 0 \\
\bottomrule()
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1961}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0980}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1373}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0882}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0588}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule()
\endhead
sl\_no & 0 & 1 & 271.00 & 156.32 & 1.00 & 136.00 & 271.00 & 406.00 &
541.00 & ▇▇▇▇▇ \\
patient\_file\_no & 0 & 1 & 271.00 & 156.32 & 1.00 & 136.00 & 271.00 &
406.00 & 541.00 & ▇▇▇▇▇ \\
pcos\_y\_n & 0 & 1 & 0.33 & 0.47 & 0.00 & 0.00 & 0.00 & 1.00 & 1.00 &
▇▁▁▁▃ \\
age\_yrs & 0 & 1 & 31.43 & 5.41 & 20.00 & 28.00 & 31.00 & 35.00 & 48.00
& ▂▇▆▃▁ \\
weight\_kg & 0 & 1 & 59.64 & 11.03 & 31.00 & 52.00 & 59.00 & 65.00 &
108.00 & ▂▇▅▁▁ \\
height\_cm & 0 & 1 & 156.48 & 6.03 & 137.00 & 152.00 & 156.00 & 160.00 &
180.00 & ▁▇▇▂▁ \\
bmi & 0 & 1 & 24.31 & 4.06 & 12.42 & 21.64 & 24.24 & 26.63 & 38.90 &
▁▅▇▂▁ \\
blood\_group & 0 & 1 & 13.80 & 1.84 & 11.00 & 13.00 & 14.00 & 15.00 &
18.00 & ▅▅▇▁▂ \\
pulse\_rate\_bpm & 0 & 1 & 73.25 & 4.43 & 13.00 & 72.00 & 72.00 & 74.00
& 82.00 & ▁▁▁▁▇ \\
rr\_breaths\_min & 0 & 1 & 19.24 & 1.69 & 16.00 & 18.00 & 18.00 & 20.00
& 28.00 & ▇▅▂▁▁ \\
hb\_g\_dl & 0 & 1 & 11.16 & 0.87 & 8.50 & 10.50 & 11.00 & 11.70 & 14.80
& ▁▇▅▂▁ \\
cycle\_r\_i & 0 & 1 & 2.56 & 0.90 & 2.00 & 2.00 & 2.00 & 4.00 & 5.00 &
▇▁▁▃▁ \\
cycle\_length\_days & 0 & 1 & 4.94 & 1.49 & 0.00 & 4.00 & 5.00 & 5.00 &
12.00 & ▁▂▇▁▁ \\
marraige\_status\_yrs & 1 & 1 & 7.68 & 4.80 & 0.00 & 4.00 & 7.00 & 10.00
& 30.00 & ▇▆▂▁▁ \\
pregnant\_y\_n & 0 & 1 & 0.38 & 0.49 & 0.00 & 0.00 & 0.00 & 1.00 & 1.00
& ▇▁▁▁▅ \\
no\_of\_aborptions & 0 & 1 & 0.29 & 0.69 & 0.00 & 0.00 & 0.00 & 0.00 &
5.00 & ▇▁▁▁▁ \\
i\_beta\_hcg\_m\_iu\_m\_l & 0 & 1 & 664.55 & 3348.92 & 1.30 & 1.99 &
20.00 & 297.21 & 32460.97 & ▇▁▁▁▁ \\
fsh\_m\_iu\_m\_l & 0 & 1 & 14.60 & 217.02 & 0.21 & 3.30 & 4.85 & 6.41 &
5052.00 & ▇▁▁▁▁ \\
lh\_m\_iu\_m\_l & 0 & 1 & 6.47 & 86.67 & 0.02 & 1.02 & 2.30 & 3.68 &
2018.00 & ▇▁▁▁▁ \\
fsh\_lh & 0 & 1 & 6.90 & 60.69 & 0.00 & 1.42 & 2.17 & 3.96 & 1372.83 &
▇▁▁▁▁ \\
hip\_inch & 0 & 1 & 37.99 & 3.97 & 26.00 & 36.00 & 38.00 & 40.00 & 48.00
& ▁▂▇▃▂ \\
waist\_inch & 0 & 1 & 33.84 & 3.60 & 24.00 & 32.00 & 34.00 & 36.00 &
47.00 & ▂▇▇▂▁ \\
waist\_hip\_ratio & 0 & 1 & 0.89 & 0.05 & 0.76 & 0.86 & 0.89 & 0.93 &
0.98 & ▁▅▆▇▆ \\
tsh\_m\_iu\_l & 0 & 1 & 2.98 & 3.76 & 0.04 & 1.48 & 2.26 & 3.57 & 65.00
& ▇▁▁▁▁ \\
prl\_ng\_m\_l & 0 & 1 & 24.32 & 14.97 & 0.40 & 14.52 & 21.92 & 29.89 &
128.24 & ▇▃▁▁▁ \\
vit\_d3\_ng\_m\_l & 0 & 1 & 49.92 & 346.21 & 0.00 & 20.80 & 25.90 &
34.50 & 6014.66 & ▇▁▁▁▁ \\
prg\_ng\_m\_l & 0 & 1 & 0.61 & 3.81 & 0.05 & 0.25 & 0.32 & 0.45 & 85.00
& ▇▁▁▁▁ \\
rbs\_mg\_dl & 0 & 1 & 99.84 & 18.56 & 60.00 & 92.00 & 100.00 & 107.00 &
350.00 & ▇▁▁▁▁ \\
weight\_gain\_y\_n & 0 & 1 & 0.38 & 0.49 & 0.00 & 0.00 & 0.00 & 1.00 &
1.00 & ▇▁▁▁▅ \\
hair\_growth\_y\_n & 0 & 1 & 0.27 & 0.45 & 0.00 & 0.00 & 0.00 & 1.00 &
1.00 & ▇▁▁▁▃ \\
skin\_darkening\_y\_n & 0 & 1 & 0.31 & 0.46 & 0.00 & 0.00 & 0.00 & 1.00
& 1.00 & ▇▁▁▁▃ \\
hair\_loss\_y\_n & 0 & 1 & 0.45 & 0.50 & 0.00 & 0.00 & 0.00 & 1.00 &
1.00 & ▇▁▁▁▆ \\
pimples\_y\_n & 0 & 1 & 0.49 & 0.50 & 0.00 & 0.00 & 0.00 & 1.00 & 1.00 &
▇▁▁▁▇ \\
fast\_food\_y\_n & 1 & 1 & 0.51 & 0.50 & 0.00 & 0.00 & 1.00 & 1.00 &
1.00 & ▇▁▁▁▇ \\
reg\_exercise\_y\_n & 0 & 1 & 0.25 & 0.43 & 0.00 & 0.00 & 0.00 & 0.00 &
1.00 & ▇▁▁▁▂ \\
bp\_systolic\_mm\_hg & 0 & 1 & 114.66 & 7.38 & 12.00 & 110.00 & 110.00 &
120.00 & 140.00 & ▁▁▁▇▇ \\
bp\_diastolic\_mm\_hg & 0 & 1 & 76.93 & 5.57 & 8.00 & 70.00 & 80.00 &
80.00 & 100.00 & ▁▁▁▇▁ \\
follicle\_no\_l & 0 & 1 & 6.13 & 4.23 & 0.00 & 3.00 & 5.00 & 9.00 &
22.00 & ▇▆▃▁▁ \\
follicle\_no\_r & 0 & 1 & 6.64 & 4.44 & 0.00 & 3.00 & 6.00 & 10.00 &
20.00 & ▇▇▅▂▁ \\
avg\_f\_size\_l\_mm & 0 & 1 & 15.02 & 3.57 & 0.00 & 13.00 & 15.00 &
18.00 & 24.00 & ▁▁▅▇▁ \\
avg\_f\_size\_r\_mm & 0 & 1 & 15.45 & 3.32 & 0.00 & 13.00 & 16.00 &
18.00 & 24.00 & ▁▁▅▇▁ \\
endometrium\_mm & 0 & 1 & 8.48 & 2.17 & 0.00 & 7.00 & 8.50 & 9.80 &
18.00 & ▁▅▇▂▁ \\
\bottomrule()
\end{longtable}

The overview of the data reveals that sl\_no and patient\_file seem to
have the same information. The majority of observations in the last
column (x45) are missing (539 out of 541). The variables `sl\_no' and
`x45' have therefore been removed.

The names of the variables include the units of measure, making the
variable names complex. These have been simplified to facilitate
analysis. Finally, variables were mutated to the correct data types and
factor levels have been specified.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Confirm that sl\_no and patient\_file\_no are the same column}
\FunctionTok{all}\NormalTok{(}\FunctionTok{identical}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{sl\_no, data}\SpecialCharTok{$}\NormalTok{patient\_file\_no))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remove variables \textquotesingle{}sl\_no\textquotesingle{} and \textquotesingle{}x45\textquotesingle{}}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data, }\AttributeTok{select =} \SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(sl\_no,x45))}

\CommentTok{\# Rename variables to simplify them}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{id =}\NormalTok{ patient\_file\_no,}
    \AttributeTok{pcos =}\NormalTok{ pcos\_y\_n,}
    \AttributeTok{age =}\NormalTok{ age\_yrs,}
    \AttributeTok{weight =}\NormalTok{ weight\_kg,}
    \AttributeTok{height =}\NormalTok{ height\_cm,}
    \AttributeTok{pulse\_rate =}\NormalTok{ pulse\_rate\_bpm,}
    \AttributeTok{rr =}\NormalTok{ rr\_breaths\_min,}
    \AttributeTok{hb =}\NormalTok{ hb\_g\_dl,}
    \AttributeTok{cycle =}\NormalTok{ cycle\_r\_i,}
    \AttributeTok{cycle\_length =}\NormalTok{ cycle\_length\_days,}
    \AttributeTok{marriage\_status =}\NormalTok{ marraige\_status\_yrs,}
    \AttributeTok{pregnant =}\NormalTok{ pregnant\_y\_n,}
    \AttributeTok{no\_of\_abortions =}\NormalTok{ no\_of\_aborptions,}
    \AttributeTok{i\_betahcg =}\NormalTok{ i\_beta\_hcg\_m\_iu\_m\_l,}
    \AttributeTok{ii\_betahcg =}\NormalTok{ ii\_beta\_hcg\_m\_iu\_m\_l,}
    \AttributeTok{fsh =}\NormalTok{ fsh\_m\_iu\_m\_l,}
    \AttributeTok{lh =}\NormalTok{lh\_m\_iu\_m\_l,}
    \AttributeTok{fsh\_lh\_ratio =}\NormalTok{ fsh\_lh,}
    \AttributeTok{hip =}\NormalTok{ hip\_inch,}
    \AttributeTok{waist =}\NormalTok{ waist\_inch,}
    \AttributeTok{tsh =}\NormalTok{ tsh\_m\_iu\_l,}
    \AttributeTok{amh =}\NormalTok{ amh\_ng\_m\_l,}
    \AttributeTok{prl =}\NormalTok{ prl\_ng\_m\_l,}
    \AttributeTok{vitd3 =}\NormalTok{ vit\_d3\_ng\_m\_l,}
    \AttributeTok{prg =}\NormalTok{ prg\_ng\_m\_l,}
    \AttributeTok{rbs =}\NormalTok{ rbs\_mg\_dl,}
    \AttributeTok{weight\_gain =}\NormalTok{ weight\_gain\_y\_n,}
    \AttributeTok{hair\_growth =}\NormalTok{ hair\_growth\_y\_n,}
    \AttributeTok{skin\_darkening =}\NormalTok{ skin\_darkening\_y\_n,}
    \AttributeTok{hair\_loss =}\NormalTok{ hair\_loss\_y\_n,}
    \AttributeTok{pimples =}\NormalTok{ pimples\_y\_n,}
    \AttributeTok{fast\_food =}\NormalTok{ fast\_food\_y\_n,}
    \AttributeTok{reg\_exercise =}\NormalTok{ reg\_exercise\_y\_n,}
    \AttributeTok{bp\_systolic =}\NormalTok{ bp\_systolic\_mm\_hg,}
    \AttributeTok{bp\_diastolic =}\NormalTok{ bp\_diastolic\_mm\_hg,}
    \AttributeTok{avg\_f\_size\_l =}\NormalTok{ avg\_f\_size\_l\_mm,}
    \AttributeTok{avg\_f\_size\_r =}\NormalTok{ avg\_f\_size\_r\_mm,}
    \AttributeTok{endometrium =}\NormalTok{ endometrium\_mm}
\NormalTok{    )}

\CommentTok{\# Mutate variables incorrectly labelled as character to numeric and those }
\CommentTok{\# incorrectly labelled as numeric to factors}
\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{id =} \FunctionTok{as.character}\NormalTok{(id),}
         \AttributeTok{pcos =} \FunctionTok{as.factor}\NormalTok{(pcos),}
         \AttributeTok{ii\_betahcg =} \FunctionTok{case\_when}\NormalTok{(ii\_betahcg }\SpecialCharTok{==} \StringTok{"1.99."}\SpecialCharTok{\textasciitilde{}} \StringTok{"1.99"}\NormalTok{, }\CommentTok{\#I found}
                                          \CommentTok{\#this typo when exploring the missing data and}
                                          \CommentTok{\# checking the excel file of said individual}
                                          \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ii\_betahcg),}
         \AttributeTok{ii\_betahcg =} \FunctionTok{as.numeric}\NormalTok{(ii\_betahcg),}
         \AttributeTok{amh =} \FunctionTok{as.numeric}\NormalTok{(amh),}
         \AttributeTok{blood\_group =} \FunctionTok{as.factor}\NormalTok{ (blood\_group),}
         \AttributeTok{pregnant =} \FunctionTok{as.factor}\NormalTok{(pregnant),}
         \AttributeTok{weight\_gain =} \FunctionTok{as.factor}\NormalTok{(weight\_gain),}
         \AttributeTok{hair\_growth =} \FunctionTok{as.factor}\NormalTok{(hair\_growth),}
         \AttributeTok{skin\_darkening =} \FunctionTok{as.factor}\NormalTok{(skin\_darkening),}
         \AttributeTok{hair\_loss =} \FunctionTok{as.factor}\NormalTok{(hair\_loss),}
         \AttributeTok{pimples =} \FunctionTok{as.factor}\NormalTok{(pimples),}
         \AttributeTok{fast\_food =} \FunctionTok{as.factor}\NormalTok{(fast\_food),}
         \AttributeTok{reg\_exercise =} \FunctionTok{as.factor}\NormalTok{(reg\_exercise))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# The levels of binary variables are set to \textquotesingle{}No\textquotesingle{} and \textquotesingle{}Yes\textquotesingle{} to assist analysis later}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{pcos)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{pregnant)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{weight\_gain)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{hair\_growth)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{skin\_darkening)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{hair\_loss)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{pimples)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{fast\_food)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{reg\_exercise)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{blood\_group)}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{"A+"}\NormalTok{,}\StringTok{"A{-}"}\NormalTok{,}\StringTok{"B+"}\NormalTok{,}\StringTok{"B{-}"}\NormalTok{,}\StringTok{"O+"}\NormalTok{,}\StringTok{"O{-}"}\NormalTok{,}\StringTok{"AB+"}\NormalTok{,}\StringTok{"AB{-}"}\NormalTok{)}

\CommentTok{\# Overview of the cleaned data}
\FunctionTok{skim}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule()
\endhead
Name & data \\
Number of rows & 541 \\
Number of columns & 43 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 1 \\
factor & 10 \\
numeric & 32 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule()
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1389}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1528}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule()
\endhead
id & 0 & 1 & 1 & 3 & 0 & 541 & 0 \\
\bottomrule()
\end{longtable}

\textbf{Variable type: factor}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1648}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1538}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0879}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0989}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3846}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ordered
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
top\_counts
\end{minipage} \\
\midrule()
\endhead
pcos & 0 & 1 & FALSE & 2 & No: 364, Yes: 177 \\
blood\_group & 0 & 1 & FALSE & 8 & O+: 206, B+: 135, A+: 108, AB+: 42 \\
pregnant & 0 & 1 & FALSE & 2 & No: 335, Yes: 206 \\
weight\_gain & 0 & 1 & FALSE & 2 & No: 337, Yes: 204 \\
hair\_growth & 0 & 1 & FALSE & 2 & No: 393, Yes: 148 \\
skin\_darkening & 0 & 1 & FALSE & 2 & No: 375, Yes: 166 \\
hair\_loss & 0 & 1 & FALSE & 2 & No: 296, Yes: 245 \\
pimples & 0 & 1 & FALSE & 2 & No: 276, Yes: 265 \\
fast\_food & 1 & 1 & FALSE & 2 & Yes: 278, No: 262 \\
reg\_exercise & 0 & 1 & FALSE & 2 & No: 407, Yes: 134 \\
\bottomrule()
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1633}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1020}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1429}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0612}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule()
\endhead
age & 0 & 1 & 31.43 & 5.41 & 20.00 & 28.00 & 31.00 & 35.00 & 48.00 &
▂▇▆▃▁ \\
weight & 0 & 1 & 59.64 & 11.03 & 31.00 & 52.00 & 59.00 & 65.00 & 108.00
& ▂▇▅▁▁ \\
height & 0 & 1 & 156.48 & 6.03 & 137.00 & 152.00 & 156.00 & 160.00 &
180.00 & ▁▇▇▂▁ \\
bmi & 0 & 1 & 24.31 & 4.06 & 12.42 & 21.64 & 24.24 & 26.63 & 38.90 &
▁▅▇▂▁ \\
pulse\_rate & 0 & 1 & 73.25 & 4.43 & 13.00 & 72.00 & 72.00 & 74.00 &
82.00 & ▁▁▁▁▇ \\
rr & 0 & 1 & 19.24 & 1.69 & 16.00 & 18.00 & 18.00 & 20.00 & 28.00 &
▇▅▂▁▁ \\
hb & 0 & 1 & 11.16 & 0.87 & 8.50 & 10.50 & 11.00 & 11.70 & 14.80 &
▁▇▅▂▁ \\
cycle & 0 & 1 & 2.56 & 0.90 & 2.00 & 2.00 & 2.00 & 4.00 & 5.00 &
▇▁▁▃▁ \\
cycle\_length & 0 & 1 & 4.94 & 1.49 & 0.00 & 4.00 & 5.00 & 5.00 & 12.00
& ▁▂▇▁▁ \\
marriage\_status & 1 & 1 & 7.68 & 4.80 & 0.00 & 4.00 & 7.00 & 10.00 &
30.00 & ▇▆▂▁▁ \\
no\_of\_abortions & 0 & 1 & 0.29 & 0.69 & 0.00 & 0.00 & 0.00 & 0.00 &
5.00 & ▇▁▁▁▁ \\
i\_betahcg & 0 & 1 & 664.55 & 3348.92 & 1.30 & 1.99 & 20.00 & 297.21 &
32460.97 & ▇▁▁▁▁ \\
ii\_betahcg & 0 & 1 & 238.23 & 1603.83 & 0.99 & 1.99 & 1.99 & 97.63 &
25000.00 & ▇▁▁▁▁ \\
fsh & 0 & 1 & 14.60 & 217.02 & 0.21 & 3.30 & 4.85 & 6.41 & 5052.00 &
▇▁▁▁▁ \\
lh & 0 & 1 & 6.47 & 86.67 & 0.02 & 1.02 & 2.30 & 3.68 & 2018.00 &
▇▁▁▁▁ \\
fsh\_lh\_ratio & 0 & 1 & 6.90 & 60.69 & 0.00 & 1.42 & 2.17 & 3.96 &
1372.83 & ▇▁▁▁▁ \\
hip & 0 & 1 & 37.99 & 3.97 & 26.00 & 36.00 & 38.00 & 40.00 & 48.00 &
▁▂▇▃▂ \\
waist & 0 & 1 & 33.84 & 3.60 & 24.00 & 32.00 & 34.00 & 36.00 & 47.00 &
▂▇▇▂▁ \\
waist\_hip\_ratio & 0 & 1 & 0.89 & 0.05 & 0.76 & 0.86 & 0.89 & 0.93 &
0.98 & ▁▅▆▇▆ \\
tsh & 0 & 1 & 2.98 & 3.76 & 0.04 & 1.48 & 2.26 & 3.57 & 65.00 & ▇▁▁▁▁ \\
amh & 1 & 1 & 5.62 & 5.88 & 0.10 & 2.01 & 3.70 & 6.93 & 66.00 & ▇▁▁▁▁ \\
prl & 0 & 1 & 24.32 & 14.97 & 0.40 & 14.52 & 21.92 & 29.89 & 128.24 &
▇▃▁▁▁ \\
vitd3 & 0 & 1 & 49.92 & 346.21 & 0.00 & 20.80 & 25.90 & 34.50 & 6014.66
& ▇▁▁▁▁ \\
prg & 0 & 1 & 0.61 & 3.81 & 0.05 & 0.25 & 0.32 & 0.45 & 85.00 & ▇▁▁▁▁ \\
rbs & 0 & 1 & 99.84 & 18.56 & 60.00 & 92.00 & 100.00 & 107.00 & 350.00 &
▇▁▁▁▁ \\
bp\_systolic & 0 & 1 & 114.66 & 7.38 & 12.00 & 110.00 & 110.00 & 120.00
& 140.00 & ▁▁▁▇▇ \\
bp\_diastolic & 0 & 1 & 76.93 & 5.57 & 8.00 & 70.00 & 80.00 & 80.00 &
100.00 & ▁▁▁▇▁ \\
follicle\_no\_l & 0 & 1 & 6.13 & 4.23 & 0.00 & 3.00 & 5.00 & 9.00 &
22.00 & ▇▆▃▁▁ \\
follicle\_no\_r & 0 & 1 & 6.64 & 4.44 & 0.00 & 3.00 & 6.00 & 10.00 &
20.00 & ▇▇▅▂▁ \\
avg\_f\_size\_l & 0 & 1 & 15.02 & 3.57 & 0.00 & 13.00 & 15.00 & 18.00 &
24.00 & ▁▁▅▇▁ \\
avg\_f\_size\_r & 0 & 1 & 15.45 & 3.32 & 0.00 & 13.00 & 16.00 & 18.00 &
24.00 & ▁▁▅▇▁ \\
endometrium & 0 & 1 & 8.48 & 2.17 & 0.00 & 7.00 & 8.50 & 9.80 & 18.00 &
▁▅▇▂▁ \\
\bottomrule()
\end{longtable}

\hypertarget{missing-values}{%
\subsection{2.3 Missing values}\label{missing-values}}

The missing variables are checked using the plot below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_missing}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/plot missing data-1.pdf} One
missing value is recorded for the variables fast\_food, marriage\_status
and amh. The code below aims to determine whether the missing data
points are all for the same person.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(fast\_food) }\SpecialCharTok{|} 
           \FunctionTok{is.na}\NormalTok{(marriage\_status) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(amh)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(id, fast\_food, marriage\_status, amh)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llrr@{}}
\toprule()
id & fast\_food & marriage\_status & amh \\
\midrule()
\endhead
157 & NA & 5 & 5.27 \\
306 & No & 9 & NA \\
459 & No & NA & 6.60 \\
\bottomrule()
\end{longtable}

We can observe that the individuals with missing observations are
different, and thus these observations (rows) do not need to be removed
at this stage. If missing variables end up in the training data set,
these will be managed with multiple imputation.

\hypertarget{variation-in-continuous-variables}{%
\subsection{3 Variation in continuous
variables}\label{variation-in-continuous-variables}}

The variation of continuous variables in the dataset are explored using
the histograms below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_histogram}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-3-1.pdf}
\includegraphics{EDA_files/figure-latex/unnamed-chunk-3-2.pdf}

From the plots, we can appreciate a few key observations. The patients
are aged between 20 and 48 with a large proportion being classed
according to their body mass index (BMI) as having a healthy weight
(18.5-24.9) or being overweight (25.0-29.9). Most women are either not
married or have been married for less than 10 years, and the majority
have not had a miscarriage/abortion. Many continuous variables seem to
follow a normal distribution, however, several variables seem to suffer
from little to no variation, possibly due to outliers. Outliers will be
examined in detail.

\hypertarget{outliers}{%
\subsubsection{3.1 Outliers}\label{outliers}}

We can observe that the variables prg, vit\_d3, fsh\_lh, fsh,
i\_betahcg, ii\_betahcg, lh and pulse\_rate seem to have no variation.
This could be happening because of the presence of outliers that make
the data look like if it were invariant, or because of the data is not
normally distributed in these variables. This can be checked by
observing the summary of said variables. These are explored in detail.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(prg, vitd3, fsh\_lh\_ratio, fsh, i\_betahcg, ii\_betahcg, lh, pulse\_rate) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rownames\_to\_column}\NormalTok{(}\AttributeTok{var =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pivot\_longer}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ID, }\AttributeTok{names\_to =} \StringTok{"variables"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"data"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(variables) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(data, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
            \AttributeTok{q1 =} \FunctionTok{quantile}\NormalTok{(data, }\FloatTok{0.25}\NormalTok{),}
            \AttributeTok{median =} \FunctionTok{quantile}\NormalTok{(data, }\FloatTok{0.5}\NormalTok{),}
            \AttributeTok{q3 =} \FunctionTok{quantile}\NormalTok{(data,}\FloatTok{0.75}\NormalTok{),}
            \AttributeTok{max =} \FunctionTok{max}\NormalTok{(data), }
            \AttributeTok{min =} \FunctionTok{min}\NormalTok{(data)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1688}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1558}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1299}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1299}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1299}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
variables
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} \\
\midrule()
\endhead
fsh & 14.6018318 & 3.300000 & 4.850000 & 6.410000 & 5052.000 &
0.2100000 \\
fsh\_lh\_ratio & 6.9048308 & 1.416244 & 2.169231 & 3.959184 & 1372.826 &
0.0021457 \\
i\_betahcg & 664.5492348 & 1.990000 & 20.000000 & 297.210000 & 32460.970
& 1.3000000 \\
ii\_betahcg & 238.2329926 & 1.990000 & 1.990000 & 97.630000 & 25000.000
& 0.9900000 \\
lh & 6.4699187 & 1.020000 & 2.300000 & 3.680000 & 2018.000 &
0.0200000 \\
prg & 0.6109445 & 0.250000 & 0.320000 & 0.450000 & 85.000 & 0.0470000 \\
pulse\_rate & 73.2476895 & 72.000000 & 72.000000 & 74.000000 & 82.000 &
13.0000000 \\
vitd3 & 49.9158743 & 20.800000 & 25.900000 & 34.500000 & 6014.660 &
0.0000000 \\
\bottomrule()
\end{longtable}

By looking at the median and quartiles, we can observe that the data
looks not to be normally distributed because there are outliers that
drag the distributions. I will check which samples are outliers for each
of these variables.

\hypertarget{fsh-hormone}{%
\paragraph{3.1.1. FSH hormone}\label{fsh-hormone}}

Now, I will look for outliers in the FSH hormone

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# FSH hormone}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"fsh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ fsh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_log10}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(fsh }\SpecialCharTok{\textgreater{}} \DecValTok{1000}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "330"
\end{verbatim}

According to
\href{https://www.mountsinai.org/health-library/tests/follicle-stimulating-hormone-fsh-blood-test}{reference
values}, this sample has an impossible biological value. Therefore, this
observation and related variables will be set to NA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{id }\SpecialCharTok{==} \DecValTok{330}\NormalTok{,}\StringTok{"fsh"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{id }\SpecialCharTok{==} \DecValTok{330}\NormalTok{,}\StringTok{"fsh\_lh\_ratio"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}
\end{Highlighting}
\end{Shaded}

The values will be log-10 transformed because looking at the quartiles
above, data is compressed in the left side of the histogram

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fsh =} \FunctionTok{log10}\NormalTok{(fsh))}

\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"fsh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ fsh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/m-1.pdf}

\hypertarget{lh-hormone}{%
\paragraph{3.1.2. LH hormone}\label{lh-hormone}}

Now, I will look for outliers in the LH hormone

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# LH hormone }
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"lh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ lh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(lh }\SpecialCharTok{\textgreater{}} \DecValTok{1000}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "456"
\end{verbatim}

The individual 456 has a LH level outside of the reported
\href{https://www.urmc.rochester.edu/encyclopedia/content.aspx?ContentTypeID=167\&ContentID=luteinizing_hormone_blood}{reference
levels}. Therefore, this value will be set to NA and the variable will
be log10-transformed. It is worth noticing that this individual is
different to the one that had an anomalous FSH level, which supports the
hypothesis if these values being technical mistakes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{id }\SpecialCharTok{==} \DecValTok{456}\NormalTok{,}\StringTok{"lh"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{id }\SpecialCharTok{==} \DecValTok{456}\NormalTok{,}\StringTok{"fsh\_lh\_ratio"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}

\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{lh =} \FunctionTok{log10}\NormalTok{(lh))}

\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"lh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ lh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-8-1.pdf}

\hypertarget{fshlh-ratio}{%
\paragraph{3.1.3. FSH/LH ratio}\label{fshlh-ratio}}

Since I have already removed outliers from the FSH and LH variables, the
remaining outlier here should be occurring biologically. Therefore, this
variable has simply been log-10 transformed.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# FSH/LH ratio}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"fsh\_lh\_ratio"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ fsh\_lh\_ratio)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(fsh\_lh\_ratio }\SpecialCharTok{\textgreater{}} \DecValTok{250}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "251"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#I will flag this patient in case it pops out somewhere else in the analysis. }

\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fsh\_lh\_ratio =} \FunctionTok{log10}\NormalTok{(fsh\_lh\_ratio))}

\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"fsh\_lh\_ratio"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ fsh\_lh\_ratio)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-9-2.pdf}

\hypertarget{human-chorionic-gonadotropin-hcg-in-the-blood}{%
\paragraph{3.1.4. Human chorionic gonadotropin (hCG) in the
blood}\label{human-chorionic-gonadotropin-hcg-in-the-blood}}

According to
\href{https://americanpregnancy.org/getting-pregnant/hcg-levels/}{reference
levels}, the values present in our dataset are within the expected
biological range. Therefore, no outlers have been removed.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Review the beta{-}HCG data (transformed for illustrative purposes) divided between the two tests and based on pregnancy status}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(id, i\_betahcg,ii\_betahcg, pregnant)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{i\_betahcg =} \FunctionTok{log10}\NormalTok{(i\_betahcg),}
         \AttributeTok{ii\_betahcg =} \FunctionTok{log10}\NormalTok{(ii\_betahcg)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}\SpecialCharTok{{-}} \FunctionTok{c}\NormalTok{(id,pregnant), }\AttributeTok{names\_to =} \StringTok{"test"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"data"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ test, }\AttributeTok{y =}\NormalTok{ data)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha=} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \FunctionTok{log10}\NormalTok{(}\DecValTok{5}\NormalTok{))}\SpecialCharTok{+} 
  \FunctionTok{facet\_grid}\NormalTok{(}\StringTok{"pregnant"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-10-1.pdf}

We can observe that even though both tests are supposed to measure the
same hormone in blood, they do not provide similar results for many
cases and there is no explanation in the data dictionary to indicate why
two test results have been obtained - i.e.~whether these are meaasured
at different time points or whether different ways of testing beta-HCG
were used. Due to this lack of information, using them in any models
would be difficult as the interpretability and reproducibility of the
model using these variables would be limited. It should be noted that
non-pregnant women are supposed to have a beta-HCG level of less than 5
mIU/mL. However, this condition is not met for several non-pregnant
women, even though overall levels in pregnant women seem to be higher.
This may be because women did not know they were pregnant. Also, it is
unclear from the data dictionary whether the pregnancy variable relates
to women who are currently pregnant or have had previous pregnancies.

\hypertarget{progesterone}{%
\paragraph{3.1.5. Progesterone}\label{progesterone}}

According to
\href{https://www.urmc.rochester.edu/encyclopedia/content.aspx?ContentTypeID=167\&ContentID=progesterone}{reference
levels}, the values in the data set seem to be biologically possible.
Therefore, only log-10 transformation of the data will be conducted.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"prg"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ prg, }\AttributeTok{color =}\NormalTok{ pregnant)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prg =} \FunctionTok{log10}\NormalTok{(prg)) }

\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"prg"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ prg, }\AttributeTok{color =}\NormalTok{ pregnant)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-11-2.pdf}

Progesterone levels are very variable depending on the mentstrual cycle
stage of the person at the time of the blood test, thus all values are
plausible. Non-pregnant women might have a progesterone concentration of
up to 25 ng/mL in the luteal stage of the menstrual cycle, which would
explain the one high value in the plot above.

\hypertarget{vitamin-d3}{%
\paragraph{3.1.6. Vitamin D3}\label{vitamin-d3}}

It has been reported that a normal range of vitamin D is 30 to 74 ng/mL,
and that
\href{https://www.uspharmacist.com/article/vitamin-d-supplementation-an-update}{side
effects and toxicity occur when blood concentrations reach 88 ng/mL or
greater}. Therefore, the outliers shown below with values over 5000
ng/mL are not biologically plausible and have therefore been set to NA.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize values of Vitamin D3}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"vitd3"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ vitd3)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remove the biologically implausible values}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(vitd3 }\SpecialCharTok{\textgreater{}} \DecValTok{90}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "192" "196"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{vitd3}\SpecialCharTok{\textgreater{}}\DecValTok{90}\NormalTok{,}\StringTok{"vitd3"}\NormalTok{] }\OtherTok{=} \ConstantTok{NA}

\CommentTok{\#Plot the data again}

\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"vitd3"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ vitd3)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-13-1.pdf}

\hypertarget{pulse-rate}{%
\paragraph{3.1.7. Pulse rate}\label{pulse-rate}}

It is reported that the normal pulse rate goes from
\href{https://www.bhf.org.uk/informationsupport/heart-matters-magazine/medical/ask-the-experts/pulse-rate}{60
to 100 bpm}. Some atheletes can have a
\href{https://my.clevelandclinic.org/health/diagnostics/17402-pulse--heart-rate}{presting
heart rate closer to 40}, however, anything less is not compatible with
life. Therefore, the two values below 20 found in our data set will be
set to NA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"pulse\_rate"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ pulse\_rate)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(pulse\_rate }\SpecialCharTok{\textless{}} \DecValTok{40}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "224" "297"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{pulse\_rate }\SpecialCharTok{\textless{}} \DecValTok{40}\NormalTok{,}\StringTok{"pulse\_rate"}\NormalTok{] }\OtherTok{=} \ConstantTok{NA}

\CommentTok{\#Re plot the data}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"pulse\_rate"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ pulse\_rate)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-14-2.pdf}

\hypertarget{thyroid-stimulating-hormone-tsh}{%
\paragraph{3.1.8.Thyroid Stimulating Hormone
(TSH)}\label{thyroid-stimulating-hormone-tsh}}

Now, I will look for outliers in the TSH hormone

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"tsh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ tsh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-15-1.pdf}

There is an outlier within our data, with a value of over 60 mIU/ml that
is above the usual level in women with PCOS, which is around
\href{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7812530/}{6.4 ±4.2
mIU/L}. However, values above 100 are
\href{https://doi.org/10.3121/cmr.2016.1309}{encountered in clinical
practice}. Thus, this value seems biologically plausible and will be
retained.

\hypertarget{anti-mullerian-hormone-amh}{%
\paragraph{3.1.9. Anti-Mullerian Hormone
(AMH)}\label{anti-mullerian-hormone-amh}}

Now, I will look for outliers in the AMH hormone

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"amh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ amh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify the patient with a high AMH level}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(amh }\SpecialCharTok{\textgreater{}} \DecValTok{48}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "268"
\end{verbatim}

I will remove the observation with AMH levels \textgreater{} 60 ng/mL
since the reported values for women with PCOS have been reported to be
around 4.32 ng/mL (2.633--7.777) in
\href{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5895547/}{previous
studies} and even in studies of women with ultra high AMH values, the
highest recorded value was
\href{https://doi.org/10.1016/j.fertnstert.2013.07.1610}{48 ng/ml}.There
are other values that seem to be too high, but only one is implausible
and will therefore be set to NA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{id }\SpecialCharTok{==} \DecValTok{268}\NormalTok{,}\StringTok{"amh"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}

\CommentTok{\#Transform the variable}
\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{amh =} \FunctionTok{log10}\NormalTok{(amh))}

\CommentTok{\#Re plot the data}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"amh"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ amh)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-17-1.pdf}

\hypertarget{blood-pressure}{%
\paragraph{3.1.10. Blood pressure}\label{blood-pressure}}

Now, I will look for outliers in the blood presure.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"bp\_systolic"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ bp\_systolic)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"bp\_diastolic"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ bp\_diastolic)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-18-2.pdf}

We can observe that there are two different atypical patients with a
very odd blood presure. Both of them have a diastolic or systolic blood
presure of almost 0 mm/Hg, which is impossible for a living human being.
Then, both of them have been set to NA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(bp\_diastolic }\SpecialCharTok{\textless{}} \DecValTok{50} \SpecialCharTok{|}\NormalTok{bp\_systolic }\SpecialCharTok{\textless{}} \DecValTok{50}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "162" "201"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#I will flag this patient in case it pops out somewhere else in the analysis.}
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{bp\_diastolic }\SpecialCharTok{\textless{}} \DecValTok{15}\NormalTok{,}\StringTok{"bp\_diastolic"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}
\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{bp\_systolic }\SpecialCharTok{\textless{}} \DecValTok{15}\NormalTok{,}\StringTok{"bp\_systolic"}\NormalTok{ ] }\OtherTok{=} \ConstantTok{NA}

\CommentTok{\#Re plot the data}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"bp\_systolic"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ bp\_systolic)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"bp\_diastolic"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ bp\_diastolic)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-19-2.pdf}

\hypertarget{random-blood-sugar-glucose-test}{%
\paragraph{3.1.11. Random blood sugar (glucose)
test}\label{random-blood-sugar-glucose-test}}

Now, I will look for outliers in the random blood sugar (glucose) test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"rbs"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ rbs)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-20-1.pdf}

According to the
\href{https://www.mayoclinic.org/diseases-conditions/diabetic-coma/symptoms-causes/syc-20371475}{literature},
glucose levels can go as up as the ones that are observed. This would
likely imply the existence of a syndrome, as well as many physiological
consequences. Since this value is then biologically possible, it will be
retained. However, the variable will be log-10 transformed.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Transform the variable}
\NormalTok{data }\OtherTok{=}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{rbs =} \FunctionTok{log10}\NormalTok{(rbs))}

\CommentTok{\#Re plot the data}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"rbs"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ rbs)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-21-1.pdf}

\hypertarget{other}{%
\paragraph{3.1.12. Other}\label{other}}

Other biological continuous variables were checked for outliers, but in
view of no significant outliers, these variables were not further
investigated or transformed.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for weight}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"weight"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ weight)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for height}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"height"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ height)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for blood mass index (BMI)}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"bmi"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ bmi)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for hemoglobin (hb)}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"hb"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ hb)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for respiratory rate (RR)}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"rr"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ rr)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for prolactin (prl)}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"prl"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ prl)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for hip circumference}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"hip"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ hip)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-7.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot to identify outliers for waist circumference}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{"waist"}\NormalTok{, }\AttributeTok{y =}\NormalTok{ waist)) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-22-8.pdf}

\hypertarget{variablity-following-data-transformations-and-outlier-analysis}{%
\subsubsection{3.2 Variablity following data transformations and outlier
analysis}\label{variablity-following-data-transformations-and-outlier-analysis}}

The variables arer rerplotted below to see how the distribution of the
variables has changed and the number of missing variables in the
dataset, which now stands at 14 compared to the initial 3 missing
values.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_histogram}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-23-1.pdf}
\includegraphics{EDA_files/figure-latex/unnamed-chunk-23-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_missing}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-23-3.pdf}

The code demonstrates that the missing data points are all for different
individuals, thus supporting the assumption that they are missing
randomly and may be random transcription errors.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(fast\_food) }\SpecialCharTok{|} 
           \FunctionTok{is.na}\NormalTok{(marriage\_status) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(amh) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(fsh) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(lh) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(vitd3) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(pulse\_rate) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(bp\_diastolic) }\SpecialCharTok{|}
           \FunctionTok{is.na}\NormalTok{(bp\_systolic)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(id, fast\_food, marriage\_status, amh, fsh, lh, vitd3, pulse\_rate, bp\_diastolic, bp\_systolic)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0385}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0962}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1538}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1058}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0962}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1058}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0577}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1058}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1250}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1154}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
id
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
fast\_food
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
marriage\_status
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
amh
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
fsh
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
lh
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vitd3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pulse\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
bp\_diastolic
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
bp\_systolic
\end{minipage} \\
\midrule()
\endhead
157 & NA & 5 & 0.7218106 & 0.4899585 & -0.2291480 & 25.30 & 72 & 70 &
120 \\
162 & No & 18 & -0.3467875 & 0.3979400 & 0.4031205 & 24.00 & 75 & 80 &
NA \\
192 & Yes & 8 & 0.8068580 & 0.5599066 & 0.0086002 & NA & 74 & 70 &
120 \\
196 & Yes & 14 & 0.8228216 & 1.3424227 & 0.5301997 & NA & 72 & 80 &
120 \\
201 & Yes & 10 & 0.0170333 & 0.9537597 & 0.4913617 & 22.00 & 73 & NA &
120 \\
224 & Yes & 5 & 0.8920946 & 0.8475727 & 0.6117233 & 31.80 & NA & 70 &
120 \\
268 & Yes & 1 & NA & 0.8662873 & 0.5575072 & 30.20 & 72 & 80 & 120 \\
297 & No & 12 & 1.0334238 & 0.8259451 & 0.7101174 & 24.90 & NA & 70 &
110 \\
306 & No & 9 & NA & 0.4638930 & -0.4559320 & 38.60 & 74 & 70 & 120 \\
330 & Yes & 5 & 0.5440680 & NA & 0.5658478 & 28.60 & 72 & 80 & 110 \\
456 & No & 12 & 0.8864907 & 0.6364879 & NA & 41.04 & 70 & 80 & 110 \\
459 & No & NA & 0.8195439 & 0.2148438 & -0.7695511 & 20.80 & 72 & 80 &
120 \\
\bottomrule()
\end{longtable}

\hypertarget{variation-in-categorical-variables}{%
\subsection{4. Variation in categorical
variables}\label{variation-in-categorical-variables}}

The variation of the categorical variables is displayed below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_bar}\NormalTok{(data }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{           dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{id))}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-25-1.pdf}
\includegraphics{EDA_files/figure-latex/unnamed-chunk-25-2.pdf}
Importanly, we can observe a class imbalance in our response variable
(diagnosis of PCOS) with 364 patients that arre negative for PCOS and
172 with a diagnosis of PCOS. Interestingly, presence of pimples,
consumption of fast food and hair loss seem to be present and absent in
almost an equal number of patients. None of the variables show an
important lack of variation.

\hypertarget{correlations-between-variables}{%
\subsection{5. Correlations between
variables}\label{correlations-between-variables}}

Finally, covariation of all of the variables in the dataset will be
explore to see if there's any strong correlation that needs to be
accounted for.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_correlation}\NormalTok{(data }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{                   dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{id), }
                 \AttributeTok{type =} \StringTok{\textquotesingle{}all\textquotesingle{}}\NormalTok{,}
                 \AttributeTok{cor\_args =} \FunctionTok{list}\NormalTok{(}\StringTok{"use"} \OtherTok{=} \StringTok{"complete.obs"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-26-1.pdf}

The correlation plot reveals some variables that are directly correlated
with our outcome of interest (i.e.~diagnosis of PCOS). These include
skin darkening, hair growth, weight gain, cycle length and number of
follicles in each ovary. This is unsurprising, as these are all
recognized features or diagnostic criteria for PCOS. However, fast food
seems to also be correlated with PCOS. Whilst a change in diet to a more
western diet of processed and fast food has been suggested to be
involved in the increasing prevalence of PCOS, the physiological
mechanism for this is not clear. Consumption of fast food is not often
part of the diagnostic criteria or risk factors considered in the
diagnosis of PCOS. The features least correlated with a diagnosis of
PCOS seem to be blood group, pregnancy status, beta-HCG, and respiratory
rate. This finding is expected as none of these variables have been
linked to PCOS in the scientific literature. Some other interesting
correlations can be gleamed from this plot. Namely that fast food is
correlated with weight gain, hair growth, hair loss, pimples, skin
darkening and follicle numbers in both ovaries, all of which are also
correlated with a diagnosis of PCOS. This is an unexpected and
interesting finding, and raises questions about the relationship between
PCOS and the consumption of fast food. Finally, some expected
correlations are noted. Pregnancy is strongly correlated with beta-HCG
values, which are normally elevated in pregnancy. Hip and waist
circumferences, which are measures used to denote central obesity, are
correlated with weight and body mass index. Weight gain is similarly
correlated with hip and waist circumference, weight and body mass index.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlation plot for all variables that have a correlation of \textgreater{}0.35 with the outcome of interest}

\NormalTok{figure5}\FloatTok{.1} \OtherTok{\textless{}{-}} \FunctionTok{plot\_correlation}\NormalTok{(data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{na.omit}\NormalTok{(data) }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(pcos, cycle, fast\_food, weight\_gain, hair\_growth, skin\_darkening, follicle\_no\_l, follicle\_no\_r), }
                              \AttributeTok{type =} \StringTok{\textquotesingle{}all\textquotesingle{}}\NormalTok{,}
                              \AttributeTok{theme\_config =} \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{, }\AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size=}\DecValTok{12}\NormalTok{), }\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{90}\NormalTok{)),}
                              \AttributeTok{cor\_args =} \FunctionTok{list}\NormalTok{(}\StringTok{"use"} \OtherTok{=} \StringTok{"complete.obs"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-27-1.pdf}

\hypertarget{associations-between-variables}{%
\subsection{6. Associations between
variables}\label{associations-between-variables}}

\hypertarget{variables-excluded-from-the-data-used-for-models}{%
\subsubsection{6.1 Variables excluded from the data used for
models}\label{variables-excluded-from-the-data-used-for-models}}

Several variables have not been included in the data used to build our
predictive diagnostic models for PCOS. These were parameters related to
infertility (pregnancy, beta human chorionic gonadotropin levels) and
those without clear evidence of association with PCOS (marital status,
blood group, thyroid stimulating hormone levels, respiratory and pulse
rate, hemoglobin). In this section, we explore the association of these
variables with a diagnosis of PCOS (i.e.~outcome of interest) to further
justify their removal from the machine learning models.

Two additional packages \emph{epiDisplay} and \emph{gmodels} need to be
loaded (and installed if not done previously) to visualize the
associations.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(epiDisplay)}
\FunctionTok{library}\NormalTok{(gmodels)}
\end{Highlighting}
\end{Shaded}

\hypertarget{pregnancy}{%
\paragraph{6.1.1 Pregnancy}\label{pregnancy}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Table and chi squared test to summarize association between pregnancy and diagnosis of PCOS}
\NormalTok{table6.}\FloatTok{1.1} \OtherTok{\textless{}{-}} \FunctionTok{CrossTable}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{pregnant, data}\SpecialCharTok{$}\NormalTok{pcos, }\AttributeTok{prop.t=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.r=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.c=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{expected =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.chisq=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{chisq =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Pregnant"}\NormalTok{,}\StringTok{"PCOS Diagnosis"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Col Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  541 
## 
##  
##              | PCOS Diagnosis 
##     Pregnant |        No |       Yes | Row Total | 
## -------------|-----------|-----------|-----------|
##           No |       222 |       113 |       335 | 
##              |     0.610 |     0.638 |           | 
## -------------|-----------|-----------|-----------|
##          Yes |       142 |        64 |       206 | 
##              |     0.390 |     0.362 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |       364 |       177 |       541 | 
##              |     0.673 |     0.327 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson's Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  0.4110566     d.f. =  1     p =  0.5214337 
## 
## Pearson's Chi-squared test with Yates' continuity correction 
## ------------------------------------------------------------
## Chi^2 =  0.2989687     d.f. =  1     p =  0.5845297 
## 
## 
\end{verbatim}

There is no statistically significant difference between patients with
and without PCOS with regards to pregnancy status (χ(1) = 0.411, p =
0.521). This further supports the decision to not use this variable in
the predictive models.

\hypertarget{beta-hcg-levels}{%
\paragraph{6.1.2 beta-HCG levels}\label{beta-hcg-levels}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize beta{-}HCG levels between patients with and without PCOS for both types of beta{-}HCG test}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, i\_betahcg)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-30-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, ii\_betahcg)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-30-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for both types of beta{-}HCG test}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(i\_betahcg, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(i\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(i\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  729. 3540.
## 2 Yes     177  532. 2923.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(ii\_betahcg, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(ii\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(ii\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  224. 1437.
## 2 Yes     177  268. 1906.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for both types of beta{-}HCG test}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(i\_betahcg) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(i\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(i\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  665. 3349.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(ii\_betahcg) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(ii\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(ii\_betahcg, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  238. 1604.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in beta{-}HCG levels between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(i\_betahcg }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  i_betahcg by pcos
## t = 0.68488, df = 414.36, p-value = 0.4938
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -368.3045  762.1843
## sample estimates:
##  mean in group No mean in group Yes 
##          728.9824          532.0425
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(ii\_betahcg }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  ii_betahcg by pcos
## t = -0.26928, df = 276.53, p-value = 0.7879
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -362.1692  275.0111
## sample estimates:
##  mean in group No mean in group Yes 
##          223.9751          267.5542
\end{verbatim}

There is no statistically significant difference between patients with
and without PCOS with regards to beta-HCG levels (using either test i or
ii) (p = 0.4938 for test i, p = 0.7879 for test ii). This further
supports the decision to not use these variables in the predictive
models.

\hypertarget{length-of-marriage}{%
\paragraph{6.1.3 Length of marriage}\label{length-of-marriage}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize the length of marriage in years between patients with and without PCOS}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, marriage\_status)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for length of marriage in years}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(marriage\_status, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(marriage\_status, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(marriage\_status, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  8.06  4.82
## 2 Yes     177  6.90  4.70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for length of marriage in years}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(marriage\_status) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(marriage\_status, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(marriage\_status, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  7.68  4.80
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in length of marriage in years between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(marriage\_status }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  marriage_status by pcos
## t = 2.6586, df = 354.04, p-value = 0.008203
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  0.3008461 2.0111294
## sample estimates:
##  mean in group No mean in group Yes 
##          8.057692          6.901705
\end{verbatim}

There is a statistically significant difference between patients with
and without PCOS with regards to length of marriage (p = 0.008203).
However, as this association does not have any basis in the
pathophysiology of PCOS, this variable will still not be used in the
predictive models.

\hypertarget{blood-group}{%
\paragraph{6.1.4 Blood group}\label{blood-group}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Table and chi squared test to summarize association between blood group and diagnosis of PCOS}
\NormalTok{table6.}\FloatTok{1.4} \OtherTok{\textless{}{-}} \FunctionTok{CrossTable}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{blood\_group, data}\SpecialCharTok{$}\NormalTok{pcos, }\AttributeTok{prop.t=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.r=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.c=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{expected =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{prop.chisq=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{chisq =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{fisher=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Blood Group"}\NormalTok{,}\StringTok{"PCOS Diagnosis"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in chisq.test(t, correct = FALSE, ...): Chi-squared approximation may be
## incorrect
\end{verbatim}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Col Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  541 
## 
##  
##              | PCOS Diagnosis 
##  Blood Group |        No |       Yes | Row Total | 
## -------------|-----------|-----------|-----------|
##           A+ |        74 |        34 |       108 | 
##              |     0.203 |     0.192 |           | 
## -------------|-----------|-----------|-----------|
##           A- |         9 |         4 |        13 | 
##              |     0.025 |     0.023 |           | 
## -------------|-----------|-----------|-----------|
##           B+ |        93 |        42 |       135 | 
##              |     0.255 |     0.237 |           | 
## -------------|-----------|-----------|-----------|
##           B- |        10 |         6 |        16 | 
##              |     0.027 |     0.034 |           | 
## -------------|-----------|-----------|-----------|
##           O+ |       140 |        66 |       206 | 
##              |     0.385 |     0.373 |           | 
## -------------|-----------|-----------|-----------|
##           O- |        11 |         8 |        19 | 
##              |     0.030 |     0.045 |           | 
## -------------|-----------|-----------|-----------|
##          AB+ |        26 |        16 |        42 | 
##              |     0.071 |     0.090 |           | 
## -------------|-----------|-----------|-----------|
##          AB- |         1 |         1 |         2 | 
##              |     0.003 |     0.006 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |       364 |       177 |       541 | 
##              |     0.673 |     0.327 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson's Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  2.048798     d.f. =  7     p =  0.9570902 
## 
## 
##  
## Fisher's Exact Test for Count Data
## ------------------------------------------------------------
## Alternative hypothesis: two.sided
## p =  0.9321499 
## 
## 
\end{verbatim}

There is no statistically significant difference between patients with
and without PCOS with regards to pregnancy status (p = 0.932). This
further supports the decision to not use this variable in the predictive
models.

\hypertarget{tsh-level}{%
\paragraph{6.1.5 TSH level}\label{tsh-level}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize the TSH level between patients with and without PCOS}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, tsh)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-33-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for TSH level}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(tsh, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(tsh, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(tsh, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  3.01  4.14
## 2 Yes     177  2.93  2.82
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for TSH level}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(tsh) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(tsh, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(tsh, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  2.98  3.76
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in TSH levels between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(tsh }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tsh by pcos
## t = 0.26727, df = 481.1, p-value = 0.7894
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -0.5150585  0.6772330
## sample estimates:
##  mean in group No mean in group Yes 
##          3.007810          2.926723
\end{verbatim}

There is no statistically significant difference between patients with
and without PCOS with regards to TSH levels (p = 0.7894). This further
supports the decision to not use this variable in the predictive models.

\hypertarget{respiratory-rate}{%
\paragraph{6.1.6 Respiratory rate}\label{respiratory-rate}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize the respiratory rate between patients with and without PCOS}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, rr)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-34-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for respiratory rate}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(rr, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(rr, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(rr, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  19.2  1.71
## 2 Yes     177  19.3  1.65
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for respiratory rate}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(rr) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(rr, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(rr, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  19.2  1.69
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in respiratory rates between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(rr }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  rr by pcos
## t = -0.86901, df = 360.66, p-value = 0.3854
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -0.4332740  0.1677062
## sample estimates:
##  mean in group No mean in group Yes 
##          19.20055          19.33333
\end{verbatim}

There is no statistically significant difference between patients with
and without PCOS with regards to respiratory rates (p = 0.3854). This
further supports the decision to not use this variable in the predictive
models.

\hypertarget{pulse-rate-1}{%
\paragraph{6.1.7 Pulse rate}\label{pulse-rate-1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize the pulse rate between patients with and without PCOS}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, pulse\_rate)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2 rows containing non-finite values (`stat_boxplot()`).
\end{verbatim}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-35-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for pulse rate}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(pulse\_rate, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(pulse\_rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(pulse\_rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  73.3  2.65
## 2 Yes     177  73.8  2.73
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for pulse rate}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(pulse\_rate) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(pulse\_rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(pulse\_rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  73.5  2.69
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in pulse rates between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(pulse\_rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  pulse_rate by pcos
## t = -2.2108, df = 340.66, p-value = 0.02771
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -1.03695253 -0.06052851
## sample estimates:
##  mean in group No mean in group Yes 
##          73.28177          73.83051
\end{verbatim}

There is a statistically significant difference between patients with
and without PCOS with regards to pulse rate (p = 0.02771). This does not
support the decision to not use this variable in the predictive models.
However, in view of the lack of evidence in the scientific literature
for including this variable, it will not be included in the model.

\hypertarget{hemoglobin}{%
\paragraph{6.1.8 Hemoglobin}\label{hemoglobin}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize hemoglobin between patients with and without PCOS}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(pcos, hb)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-36-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for hemoglobin}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(hb, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(hb, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(hb, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  11.1 0.880
## 2 Yes     177  11.3 0.831
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation overall for hemoglobin}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(hb) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(hb, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(hb, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##       n  mean    sd
##   <int> <dbl> <dbl>
## 1   541  11.2 0.867
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in hemoglobin between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(hb }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  hb by pcos
## t = -2.0728, df = 367.64, p-value = 0.03888
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -0.313569336 -0.008260613
## sample estimates:
##  mean in group No mean in group Yes 
##          11.10739          11.26831
\end{verbatim}

There is a statistically significant difference between patients with
and without PCOS with regards to hemoglobin (p = 0.03888). This does not
support the decision to not use this variable in the predictive models.
However, in view of the lack of evidence in the scientific literature
for including this variable, it will not be included in the model.

\hypertarget{variables-most-correlated-with-pcos}{%
\subsubsection{6.2 Variables most correlated with
PCOS}\label{variables-most-correlated-with-pcos}}

The two variables most correlated with PCOS according to the correlation
coefficients in figure 5.1 are the number of follicles in the left and
right ovary. The association of these two variables with a diagnosis of
PCOS will be explored in further detail below through visualization and
statistical tests.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{violin\_left }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{pcos, }\AttributeTok{y=}\NormalTok{follicle\_no\_l)) }\SpecialCharTok{+}
  \FunctionTok{geom\_violin}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{pcos), }\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{pcos), }\AttributeTok{outlier.size=}\DecValTok{2}\NormalTok{, }\AttributeTok{width=}\FloatTok{0.15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values=}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0072B2"}\NormalTok{, }\StringTok{"\#E69F00"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_discrete}\NormalTok{(}\AttributeTok{name =} \StringTok{"Diagnosis of PCOS"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{name =} \StringTok{"Number of follicles"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{guides}\NormalTok{(}\AttributeTok{fill=}\StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{(}\DecValTok{10}\NormalTok{)}

\NormalTok{violin\_right }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{pcos, }\AttributeTok{y=}\NormalTok{follicle\_no\_r)) }\SpecialCharTok{+}
  \FunctionTok{geom\_violin}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{pcos), }\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{pcos), }\AttributeTok{outlier.size=}\DecValTok{2}\NormalTok{, }\AttributeTok{width=}\FloatTok{0.15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values=}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0072B2"}\NormalTok{, }\StringTok{"\#E69F00"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_discrete}\NormalTok{(}\AttributeTok{name =} \StringTok{"Diagnosis of PCOS"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{name =} \StringTok{"Number of follicles"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{guides}\NormalTok{(}\AttributeTok{fill=}\StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{(}\DecValTok{10}\NormalTok{)}

\NormalTok{figure6}\FloatTok{.2} \OtherTok{\textless{}{-}} \FunctionTok{plot\_grid}\NormalTok{(violin\_left, violin\_right, }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Left Ovary\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Right Ovary\textquotesingle{}}\NormalTok{), }\AttributeTok{label\_size =} \DecValTok{10}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{scale =} \FloatTok{0.95}\NormalTok{)}

\FunctionTok{print}\NormalTok{(figure6}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EDA_files/figure-latex/unnamed-chunk-37-1.pdf}

There is clearly a large difference in the average number follicles in
each ovary between women with and without a diagnosis of PCOS.This
association is studied with a statistical significance test below.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for number of follicles in the left}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(follicle\_no\_l, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(follicle\_no\_l, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(follicle\_no\_l, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  4.35  2.81
## 2 Yes     177  9.79  4.31
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in the number of follicles in the left between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(follicle\_no\_l }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  follicle_no_l by pcos
## t = -15.268, df = 251.34, p-value < 2.2e-16
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -6.134571 -4.732754
## sample estimates:
##  mean in group No mean in group Yes 
##          4.351648          9.785311
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean and standard deviation by PCOS diagnosis for number of follicles in the right}
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(follicle\_no\_r, pcos) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(pcos) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{n}\NormalTok{(), }
            \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(follicle\_no\_r, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }
            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(follicle\_no\_r, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 4
##   pcos      n  mean    sd
##   <fct> <int> <dbl> <dbl>
## 1 No      364  4.64  2.93
## 2 Yes     177 10.8   4.17
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Independent t{-}test to determine if there is a difference in the number of follicles in the left between PCOS negative and positive cases}
\FunctionTok{t.test}\NormalTok{(follicle\_no\_r }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  follicle_no_r by pcos
## t = -17.569, df = 263.24, p-value < 2.2e-16
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -6.811854 -5.438844
## sample estimates:
##  mean in group No mean in group Yes 
##          4.637363         10.762712
\end{verbatim}

\hypertarget{save-clean-object}{%
\subsection{Save clean object}\label{save-clean-object}}

Finally, I will save the object for future stages of this project.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{save}\NormalTok{(data,}\AttributeTok{file =}  \FunctionTok{here}\NormalTok{(}\StringTok{"data.Rdata"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

This EDA was very helpful to familiarize myself with the data, clean it,
and identify any pattern that could potentially need to be addressed in
the future of my analysis. I was able to flag individuals with missing
observations, remove outliers, transform some variables so that they had
a higher variability range, and observe the correlation between my
variables.

\hypertarget{session-info}{%
\subsection{Session info}\label{session-info}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R version 4.2.2 (2022-10-31)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Big Sur ... 10.16
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] gmodels_2.18.1.1   epiDisplay_3.5.0.2 nnet_7.3-18        MASS_7.3-58.1     
##  [5] survival_3.4-0     foreign_0.8-83     cowplot_1.1.1      skimr_2.1.5       
##  [9] knitr_1.41         DataExplorer_0.8.2 janitor_2.1.0      readxl_1.4.1      
## [13] here_1.0.1         forcats_0.5.2      stringr_1.4.1      dplyr_1.0.10      
## [17] purrr_0.3.5        readr_2.1.3        tidyr_1.2.1        tibble_3.1.8      
## [21] ggplot2_3.4.0      tidyverse_1.3.2   
## 
## loaded via a namespace (and not attached):
##  [1] fs_1.5.2            lubridate_1.9.0     httr_1.4.4         
##  [4] rprojroot_2.0.3     repr_1.1.4          tools_4.2.2        
##  [7] backports_1.4.1     utf8_1.2.2          R6_2.5.1           
## [10] DBI_1.1.3           colorspace_2.0-3    withr_2.5.0        
## [13] tidyselect_1.2.0    gridExtra_2.3       compiler_4.2.2     
## [16] cli_3.4.1           rvest_1.0.3         xml2_1.3.3         
## [19] labeling_0.4.2      scales_1.2.1        digest_0.6.30      
## [22] rmarkdown_2.18      base64enc_0.1-3     pkgconfig_2.0.3    
## [25] htmltools_0.5.3     dbplyr_2.2.1        fastmap_1.1.0      
## [28] highr_0.9           htmlwidgets_1.5.4   rlang_1.0.6        
## [31] rstudioapi_0.14     farver_2.1.1        generics_0.1.3     
## [34] jsonlite_1.8.3      gtools_3.9.4        googlesheets4_1.0.1
## [37] magrittr_2.0.3      Matrix_1.5-1        Rcpp_1.0.9         
## [40] munsell_0.5.0       fansi_1.0.3         lifecycle_1.0.3    
## [43] stringi_1.7.8       yaml_2.3.6          snakecase_0.11.0   
## [46] plyr_1.8.8          grid_4.2.2          gdata_2.18.0.1     
## [49] parallel_4.2.2      crayon_1.5.2        lattice_0.20-45    
## [52] haven_2.5.1         splines_4.2.2       hms_1.1.2          
## [55] pillar_1.8.1        igraph_1.3.5        reshape2_1.4.4     
## [58] reprex_2.0.2        glue_1.6.2          evaluate_0.18      
## [61] data.table_1.14.6   modelr_0.1.10       vctrs_0.5.1        
## [64] tzdb_0.3.0          networkD3_0.4       cellranger_1.1.0   
## [67] gtable_0.3.1        assertthat_0.2.1    xfun_0.35          
## [70] broom_1.0.1         googledrive_2.0.0   gargle_1.2.1       
## [73] timechange_0.1.1    ellipsis_0.3.2
\end{verbatim}

\end{document}
